name: analyze

on:
  push:
    tags:
      - v*

jobs:
  scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mathrix-education/sonar-scanner@master
        with:
          version: 4.2.0.1873 # scanner version (required)
          typescript: true
          scan: true
          args: -Dsonar.login=${SONAR_TOKEN}
